language: java

addons:
  sonarcloud:
    organization: "ivandelabeldad-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - .autoconf
  - $HOME/.m2